/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author Marzena
 */
public class ClientPage extends javax.swing.JPanel implements java.beans.Customizer {
    
    private Object bean;

    /**
     * Creates new customizer ClientPage
     */
    public ClientPage() {
        initComponents();
    }
    
    public void setObject(Object bean) {
        this.bean = bean;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the FormEditor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFileChooser1 = new javax.swing.JFileChooser();
        jDesktopPane1 = new javax.swing.JDesktopPane();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jSeparator2 = new javax.swing.JSeparator();

        setLayout(new java.awt.BorderLayout());

        jDesktopPane1.setBackground(new java.awt.Color(219, 219, 253));

        jButton1.setText("Wyloguj");
        jDesktopPane1.add(jButton1);
        jButton1.setBounds(683, 10, 80, 23);

        jButton2.setText("Moje konto");
        jDesktopPane1.add(jButton2);
        jButton2.setBounds(580, 10, 85, 23);

        jTextField2.setEditable(false);
        jTextField2.setBackground(new java.awt.Color(193, 193, 255));
        jTextField2.setFont(new java.awt.Font("Sylfaen", 0, 30)); // NOI18N
        jTextField2.setForeground(new java.awt.Color(255, 255, 255));
        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Moje Karty");
        jDesktopPane1.add(jTextField2);
        jTextField2.setBounds(110, 50, 670, 40);

        jLabel1.setFont(new java.awt.Font("SketchFlow Print", 3, 24)); // NOI18N
        jLabel1.setText("Ski Station");
        jDesktopPane1.add(jLabel1);
        jLabel1.setBounds(20, 10, 170, 30);

        jButton3.setText("Natężenie stoku");
        jDesktopPane1.add(jButton3);
        jButton3.setBounds(0, 80, 110, 23);

        jButton4.setText("Kontakt");
        jDesktopPane1.add(jButton4);
        jButton4.setBounds(0, 60, 110, 23);
        jDesktopPane1.add(jScrollPane2);
        jScrollPane2.setBounds(110, 90, 670, 370);
        jDesktopPane1.add(jSeparator2);
        jSeparator2.setBounds(0, 50, 110, 410);

        add(jDesktopPane1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JDesktopPane jDesktopPane1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
