/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RegistrationController;
import Controller.LoginController;
import Model.TestClass;
import java.awt.CardLayout;


/**
 *
 * @author Adam
 */
public class MainWindow extends javax.swing.JFrame {

    private boolean userLogged;
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Login = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        LoginTextField = new javax.swing.JTextField();
        PasswordTextField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        CreateAccountLink = new javax.swing.JLabel();
        LoginBackgroundImage = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        LoginTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Surname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DocumentNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Street = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        RegisterBackgroundImage1 = new javax.swing.JLabel();
        ClientPage = new javax.swing.JPanel();
        jTextField2 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        ClientPageBackground = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        Login.setLayout(null);

        LoginButton.setText("Zaloguj");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Login.add(LoginButton);
        LoginButton.setBounds(440, 110, 80, 23);

        LoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextFieldActionPerformed(evt);
            }
        });
        Login.add(LoginTextField);
        LoginTextField.setBounds(440, 40, 220, 30);

        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        Login.add(PasswordTextField);
        PasswordTextField.setBounds(440, 70, 220, 30);

        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Hasło:");
        PasswordLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        PasswordLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        PasswordLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        Login.add(PasswordLabel);
        PasswordLabel.setBounds(370, 80, 50, 14);

        LoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginLabel.setText("Login:");
        Login.add(LoginLabel);
        LoginLabel.setBounds(370, 50, 50, 14);

        CreateAccountLink.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountLink.setText("Załóż konto");
        CreateAccountLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAccountLinkMouseClicked(evt);
            }
        });
        Login.add(CreateAccountLink);
        CreateAccountLink.setBounds(590, 110, 90, 14);

        LoginBackgroundImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpg"))); // NOI18N
        Login.add(LoginBackgroundImage);
        LoginBackgroundImage.setBounds(0, -330, 740, 1350);

        getContentPane().add(Login, "login");
        Login.getAccessibleContext().setAccessibleName("");

        Register.setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ulica:");
        jLabel8.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel8);
        jLabel8.setBounds(370, 260, 50, 14);

        LoginTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextField1ActionPerformed(evt);
            }
        });
        Register.add(LoginTextField1);
        LoginTextField1.setBounds(440, 40, 220, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hasło:");
        jLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel1);
        jLabel1.setBounds(370, 80, 50, 14);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Register.add(Password);
        Password.setBounds(440, 70, 220, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imię:");
        jLabel2.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel2);
        jLabel2.setBounds(370, 110, 50, 14);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Register.add(Name);
        Name.setBounds(440, 100, 220, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nazwisko:");
        jLabel3.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel3);
        jLabel3.setBounds(370, 140, 60, 14);

        Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameActionPerformed(evt);
            }
        });
        Register.add(Surname);
        Surname.setBounds(440, 130, 220, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Pesel:");
        Register.add(jLabel4);
        jLabel4.setBounds(370, 170, 50, 14);

        DocumentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentNumberActionPerformed(evt);
            }
        });
        Register.add(DocumentNumber);
        DocumentNumber.setBounds(440, 160, 220, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Miasto:");
        jLabel5.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel5);
        jLabel5.setBounds(370, 200, 50, 14);

        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        Register.add(City);
        City.setBounds(440, 190, 220, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Kraj:");
        jLabel6.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel6);
        jLabel6.setBounds(370, 230, 50, 14);

        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });
        Register.add(Country);
        Country.setBounds(440, 220, 220, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login:");
        Register.add(jLabel7);
        jLabel7.setBounds(370, 50, 50, 14);

        Street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetActionPerformed(evt);
            }
        });
        Register.add(Street);
        Street.setBounds(440, 250, 220, 30);

        BackButton.setText("Powrót");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Register.add(BackButton);
        BackButton.setBounds(480, 290, 80, 23);

        RegisterButton.setText("Załóż konto");
        RegisterButton.setMaximumSize(new java.awt.Dimension(67, 23));
        RegisterButton.setMinimumSize(new java.awt.Dimension(67, 23));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        Register.add(RegisterButton);
        RegisterButton.setBounds(560, 290, 100, 23);

        RegisterBackgroundImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.jpg"))); // NOI18N
        Register.add(RegisterBackgroundImage1);
        RegisterBackgroundImage1.setBounds(0, -100, 1220, 890);

        getContentPane().add(Register, "register");

        ClientPage.setMinimumSize(new java.awt.Dimension(0, 0));
        ClientPage.setPreferredSize(new java.awt.Dimension(0, 0));
        ClientPage.setLayout(null);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setToolTipText("");
        jTextField2.setEnabled(false);
        jTextField2.setRequestFocusEnabled(false);
        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });
        ClientPage.add(jTextField2);
        jTextField2.setBounds(320, 150, 50, 20);

        jButton1.setText("Moje konto");
        jButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton1);
        jButton1.setBounds(480, 10, 100, 23);

        jButton2.setText("Wyloguj");
        jButton2.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton2.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton2.setPreferredSize(new java.awt.Dimension(67, 23));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        ClientPage.add(jButton2);
        jButton2.setBounds(580, 10, 80, 23);

        jButton3.setText("Kontakt");
        jButton3.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton3.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton3.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton3);
        jButton3.setBounds(20, 120, 110, 23);

        jButton4.setText("Natężenie stoku");
        jButton4.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton4.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton4.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton4);
        jButton4.setBounds(20, 90, 110, 23);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nieprzydzielone punkty:");
        jLabel10.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel10.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel10.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientPage.add(jLabel10);
        jLabel10.setBounds(200, 150, 120, 14);

        jButton5.setText("Dodaj kartę");
        jButton5.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton5.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton5.setPreferredSize(new java.awt.Dimension(67, 23));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        ClientPage.add(jButton5);
        jButton5.setBounds(560, 150, 100, 23);

        jButton9.setText("Moje karty");
        jButton9.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton9.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton9.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton9);
        jButton9.setBounds(20, 60, 110, 23);

        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("ID");
        jLabel9.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel9.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel9.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientPage.add(jLabel9);
        jLabel9.setBounds(180, 190, 50, 14);

        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Data aktywacji");
        jLabel11.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel11.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel11.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientPage.add(jLabel11);
        jLabel11.setBounds(240, 190, 80, 14);

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Data ważności");
        jLabel12.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel12.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel12.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientPage.add(jLabel12);
        jLabel12.setBounds(330, 190, 80, 14);

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Punkty");
        jLabel13.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel13.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel13.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientPage.add(jLabel13);
        jLabel13.setBounds(420, 190, 50, 14);

        jTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField1.setToolTipText("");
        jTextField1.setEnabled(false);
        jTextField1.setPreferredSize(new java.awt.Dimension(29, 20));
        ClientPage.add(jTextField1);
        jTextField1.setBounds(180, 210, 50, 20);

        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setEnabled(false);
        jTextField3.setPreferredSize(new java.awt.Dimension(29, 20));
        ClientPage.add(jTextField3);
        jTextField3.setBounds(240, 210, 80, 20);

        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setEnabled(false);
        jTextField4.setPreferredSize(new java.awt.Dimension(29, 20));
        ClientPage.add(jTextField4);
        jTextField4.setBounds(330, 210, 80, 20);

        jTextField5.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField5.setPreferredSize(new java.awt.Dimension(29, 20));
        jTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField5ActionPerformed(evt);
            }
        });
        ClientPage.add(jTextField5);
        jTextField5.setBounds(420, 210, 50, 20);

        jButton6.setText("+");
        jButton6.setToolTipText("");
        jButton6.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton6.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton6.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton6);
        jButton6.setBounds(470, 210, 40, 20);

        jButton7.setText("-");
        jButton7.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton7.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton7.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton7);
        jButton7.setBounds(510, 210, 40, 20);

        jButton8.setText("Usuń kartę");
        jButton8.setMaximumSize(new java.awt.Dimension(67, 23));
        jButton8.setMinimumSize(new java.awt.Dimension(67, 23));
        jButton8.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientPage.add(jButton8);
        jButton8.setBounds(560, 210, 100, 23);

        ClientPageBackground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clientPage.jpg"))); // NOI18N
        ClientPage.add(ClientPageBackground);
        ClientPageBackground.setBounds(0, -100, 1220, 890);

        getContentPane().add(ClientPage, "clientPage");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void CreateAccountLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountLinkMouseClicked
        // TODO add your handling code here:
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        loginPaneLayout.show(getContentPane(), "register");
    }//GEN-LAST:event_CreateAccountLinkMouseClicked

    private void LoginTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTextField1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameActionPerformed

    private void DocumentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentNumberActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        //TestClass.test();        // TODO add your handling code here:
        if (LoginController.logIn(LoginTextField.getText(), new String(PasswordTextField.getPassword()), userLogged))
            ;//TODO change view x----DDDDDDDD
        else
            ;//TODO error message, wrong login and/or password
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void StreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        loginPaneLayout.show(getContentPane(), "login");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        RegistrationController regController = new RegistrationController();
        Boolean isSuccess = regController.register(Name.getText(), Surname.getText(), City.getText(), Country.getText(), Street.getText(), LoginTextField1.getText(), new String(Password.getPassword()), DocumentNumber.getText());
        if (isSuccess) {
            CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
            loginPaneLayout.show(getContentPane(), "login");
        }else{
            LoginTextField1.setText("");
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField5ActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BackButton;
    private javax.swing.JTextField City;
    private javax.swing.JPanel ClientPage;
    private javax.swing.JLabel ClientPageBackground;
    private javax.swing.JTextField Country;
    private javax.swing.JLabel CreateAccountLink;
    private javax.swing.JTextField DocumentNumber;
    private javax.swing.JPanel Login;
    private javax.swing.JLabel LoginBackgroundImage;
    private javax.swing.JButton LoginButton;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JTextField LoginTextField1;
    private javax.swing.JTextField Name;
    private javax.swing.JPasswordField Password;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel RegisterBackgroundImage1;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JTextField Street;
    private javax.swing.JTextField Surname;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    // End of variables declaration//GEN-END:variables
}
