/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Controller.RegistrationController;
import Controller.LoginController;
import Controller.MyAccountController;
import Controller.SessionController;
import Controller.UserManagementAdminController;
import DBClasses.*;
import java.awt.CardLayout;
import java.util.Enumeration;
import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;


/**
 *
 * @author Adam
 */
public class MainWindow extends javax.swing.JFrame {

    private StringBuilder loginStatusMessage = new StringBuilder();
    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        UserRoleChooseGroup = new javax.swing.ButtonGroup();
        jScrollPane2 = new javax.swing.JScrollPane();
        jEditorPane1 = new javax.swing.JEditorPane();
        Login = new javax.swing.JPanel();
        LoginButton = new javax.swing.JButton();
        LoginTextField = new javax.swing.JTextField();
        MessageLabel = new javax.swing.JLabel();
        PasswordTextField = new javax.swing.JPasswordField();
        PasswordLabel = new javax.swing.JLabel();
        LoginLabel = new javax.swing.JLabel();
        CreateAccountLink = new javax.swing.JLabel();
        BackgroundImageLabel = new javax.swing.JLabel();
        ActionInfoLabel = new javax.swing.JLabel();
        Register = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        RegisterMessageLabel = new javax.swing.JLabel();
        LoginTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        Password = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();
        Name = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        Surname = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        DocumentNumber = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        City = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        Country = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        Street = new javax.swing.JTextField();
        BackButton = new javax.swing.JButton();
        RegisterButton = new javax.swing.JButton();
        RegisterBackgroundImage1 = new javax.swing.JLabel();
        CashierPanel = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        UserLogoutButton1 = new javax.swing.JButton();
        ContactButton1 = new javax.swing.JButton();
        SlopeTrafficButton1 = new javax.swing.JButton();
        ClientModeButton1 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<String>();
        jLabel13 = new javax.swing.JLabel();
        ContactButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jButton4 = new javax.swing.JButton();
        UserBackgroundLabel1 = new javax.swing.JLabel();
        ClientCardsPanel = new javax.swing.JPanel();
        UserLogoutButton4 = new javax.swing.JButton();
        AvailablePointsLabel1 = new javax.swing.JLabel();
        IDLabel1 = new javax.swing.JLabel();
        ActivationDateLabel1 = new javax.swing.JLabel();
        ExpirationDateLabel1 = new javax.swing.JLabel();
        PointsLabel1 = new javax.swing.JLabel();
        AvailablePointsTextField1 = new javax.swing.JTextField();
        IDTextField1 = new javax.swing.JTextField();
        ActivationDateTextField1 = new javax.swing.JTextField();
        ExpirationDateTextField1 = new javax.swing.JTextField();
        PointsTextField1 = new javax.swing.JTextField();
        AddPointsButton1 = new javax.swing.JButton();
        SubtractPointsButton1 = new javax.swing.JButton();
        AddCardButton1 = new javax.swing.JButton();
        RemoveCardButton1 = new javax.swing.JButton();
        CashierMenuButton1 = new javax.swing.JButton();
        ClientCards = new javax.swing.JButton();
        ClientAccount = new javax.swing.JButton();
        RemoveCardButton2 = new javax.swing.JButton();
        jTextField3 = new javax.swing.JTextField();
        UserBackgroundLabel3 = new javax.swing.JLabel();
        ClientAccountPanel = new javax.swing.JPanel();
        UserMyAccountButton3 = new javax.swing.JButton();
        UserLogoutButton3 = new javax.swing.JButton();
        MyAccountLabel1 = new javax.swing.JLabel();
        EditLoginLabel1 = new javax.swing.JLabel();
        EditPasswordLabel1 = new javax.swing.JLabel();
        LoginEditTextfield1 = new javax.swing.JTextField();
        PasswordEditTextfield1 = new javax.swing.JTextField();
        NameEditTextfield1 = new javax.swing.JTextField();
        SurnameEditTextfield1 = new javax.swing.JTextField();
        NameEditLabel1 = new javax.swing.JLabel();
        SurnameEditLabel1 = new javax.swing.JLabel();
        IDEditLabel1 = new javax.swing.JLabel();
        IDEditTextfield1 = new javax.swing.JTextField();
        StreetEditTextfield1 = new javax.swing.JTextField();
        CityEditTextfield1 = new javax.swing.JTextField();
        CountryEditTextfield1 = new javax.swing.JTextField();
        StreetEditLabel1 = new javax.swing.JLabel();
        CityEditLabel1 = new javax.swing.JLabel();
        CountryEditLabel1 = new javax.swing.JLabel();
        EditDetailsButton1 = new javax.swing.JButton();
        SaveDetailsButton1 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        CancelButton1 = new javax.swing.JButton();
        EditMessageLabel1 = new javax.swing.JLabel();
        DocumentEditTextfield1 = new javax.swing.JTextField();
        ClientCards1 = new javax.swing.JButton();
        ClientAccount1 = new javax.swing.JButton();
        jTextField4 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        AdminMainPanel = new javax.swing.JPanel();
        SlopeButton = new javax.swing.JButton();
        PriceListButton = new javax.swing.JButton();
        CashierModeButton = new javax.swing.JButton();
        GatesButton = new javax.swing.JButton();
        ClientModeButton = new javax.swing.JButton();
        UsersButton = new javax.swing.JButton();
        AdminLogoutButton = new javax.swing.JButton();
        AdminMyAccountButton = new javax.swing.JButton();
        AdminBackgroundLabel = new javax.swing.JLabel();
        UserManagmenAdmintPanel = new javax.swing.JPanel();
        UpdateUser = new javax.swing.JButton();
        RemoveUser = new javax.swing.JButton();
        Back = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        FindLoginTextField = new javax.swing.JTextField();
        FindUser = new javax.swing.JButton();
        FindResultLabel = new javax.swing.JLabel();
        UserRadio = new javax.swing.JRadioButton();
        CashierRadio = new javax.swing.JRadioButton();
        AdminRadio = new javax.swing.JRadioButton();
        UpdateResultLabel = new javax.swing.JLabel();
        UserManagePanelBackgroud = new javax.swing.JLabel();
        UserMainPanel = new javax.swing.JPanel();
        UserMyAccountButton = new javax.swing.JButton();
        UserLogoutButton = new javax.swing.JButton();
        ContactButton = new javax.swing.JButton();
        MyCardsButton = new javax.swing.JButton();
        SlopeTrafficButton = new javax.swing.JButton();
        AvailablePointsLabel = new javax.swing.JLabel();
        IDLabel = new javax.swing.JLabel();
        ActivationDateLabel = new javax.swing.JLabel();
        ExpirationDateLabel = new javax.swing.JLabel();
        PointsLabel = new javax.swing.JLabel();
        AvailablePointsTextField = new javax.swing.JTextField();
        IDTextField = new javax.swing.JTextField();
        ActivationDateTextField = new javax.swing.JTextField();
        ExpirationDateTextField = new javax.swing.JTextField();
        PointsTextField = new javax.swing.JTextField();
        AddPointsButton = new javax.swing.JButton();
        SubtractPointsButton = new javax.swing.JButton();
        AddCardButton = new javax.swing.JButton();
        RemoveCardButton = new javax.swing.JButton();
        UserBackgroundLabel = new javax.swing.JLabel();
        MyAccountPanel = new javax.swing.JPanel();
        UserMyAccountButton2 = new javax.swing.JButton();
        UserLogoutButton2 = new javax.swing.JButton();
        EditLoginLabel = new javax.swing.JLabel();
        EditPasswordLabel = new javax.swing.JLabel();
        LoginEditTextfield = new javax.swing.JTextField();
        PasswordEditTextfield = new javax.swing.JTextField();
        NameEditTextfield = new javax.swing.JTextField();
        SurnameEditTextfield = new javax.swing.JTextField();
        NameEditLabel = new javax.swing.JLabel();
        SurnameEditLabel = new javax.swing.JLabel();
        IDEditLabel = new javax.swing.JLabel();
        IDEditTextfield = new javax.swing.JTextField();
        StreetEditTextfield = new javax.swing.JTextField();
        CityEditTextfield = new javax.swing.JTextField();
        CountryEditTextfield = new javax.swing.JTextField();
        StreetEditLabel = new javax.swing.JLabel();
        CityEditLabel = new javax.swing.JLabel();
        CountryEditLabel = new javax.swing.JLabel();
        EditDetailsButton = new javax.swing.JButton();
        SaveDetailsButton = new javax.swing.JButton();
        MyCardsButton2 = new javax.swing.JButton();
        SlopeTrafficButton2 = new javax.swing.JButton();
        ContactButton2 = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        CancelButton = new javax.swing.JButton();
        EditMessageLabel = new javax.swing.JLabel();
        DocumentEditTextfield = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();

        jScrollPane2.setViewportView(jEditorPane1);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(700, 700));
        setResizable(false);
        getContentPane().setLayout(new java.awt.CardLayout());

        Login.setLayout(null);

        LoginButton.setText("Zaloguj");
        LoginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginButtonActionPerformed(evt);
            }
        });
        Login.add(LoginButton);
        LoginButton.setBounds(450, 120, 80, 23);

        LoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextFieldActionPerformed(evt);
            }
        });
        Login.add(LoginTextField);
        LoginTextField.setBounds(450, 50, 220, 30);

        MessageLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        MessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        MessageLabel.setToolTipText("");
        Login.add(MessageLabel);
        MessageLabel.setBounds(450, 30, 220, 20);
        MessageLabel.getAccessibleContext().setAccessibleName("MessageLabel");

        PasswordTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordTextFieldActionPerformed(evt);
            }
        });
        Login.add(PasswordTextField);
        PasswordTextField.setBounds(450, 80, 220, 30);

        PasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        PasswordLabel.setText("Hasło:");
        Login.add(PasswordLabel);
        PasswordLabel.setBounds(370, 90, 50, 14);

        LoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        LoginLabel.setText("Login:");
        Login.add(LoginLabel);
        LoginLabel.setBounds(370, 60, 50, 14);

        CreateAccountLink.setForeground(new java.awt.Color(255, 255, 255));
        CreateAccountLink.setText("Załóż konto");
        CreateAccountLink.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CreateAccountLinkMouseClicked(evt);
            }
        });
        Login.add(CreateAccountLink);
        CreateAccountLink.setBounds(600, 120, 70, 20);

        BackgroundImageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/login.jpg"))); // NOI18N
        BackgroundImageLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Login.add(BackgroundImageLabel);
        BackgroundImageLabel.setBounds(0, 0, 1310, 890);

        ActionInfoLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActionInfoLabel.setText("Trwa logowanie... [Tu będzie jakiś obrazek przedstawiający kręcące się coś albo status bar]");
        ActionInfoLabel.setToolTipText("");
        Login.add(ActionInfoLabel);
        ActionInfoLabel.setBounds(0, 0, 750, 440);

        getContentPane().add(Login, "login");
        Login.getAccessibleContext().setAccessibleName("");

        Register.setLayout(null);

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Ulica:");
        jLabel8.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel8.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel8.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel8);
        jLabel8.setBounds(370, 270, 50, 14);

        RegisterMessageLabel.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        RegisterMessageLabel.setForeground(new java.awt.Color(255, 0, 0));
        Register.add(RegisterMessageLabel);
        RegisterMessageLabel.setBounds(450, 30, 220, 20);

        LoginTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LoginTextField1ActionPerformed(evt);
            }
        });
        Register.add(LoginTextField1);
        LoginTextField1.setBounds(450, 50, 220, 30);

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Hasło:");
        jLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel1);
        jLabel1.setBounds(370, 90, 50, 14);

        Password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PasswordActionPerformed(evt);
            }
        });
        Register.add(Password);
        Password.setBounds(450, 80, 220, 30);

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Imię:");
        jLabel2.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel2.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel2.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel2);
        jLabel2.setBounds(370, 120, 50, 14);

        Name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                NameActionPerformed(evt);
            }
        });
        Register.add(Name);
        Name.setBounds(450, 110, 220, 30);

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Nazwisko:");
        jLabel3.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel3.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel3.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel3);
        jLabel3.setBounds(370, 150, 60, 14);

        Surname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SurnameActionPerformed(evt);
            }
        });
        Register.add(Surname);
        Surname.setBounds(450, 140, 220, 30);

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Nr dokumentu:");
        jLabel4.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel4.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel4.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel4);
        jLabel4.setBounds(370, 180, 90, 14);

        DocumentNumber.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DocumentNumberActionPerformed(evt);
            }
        });
        Register.add(DocumentNumber);
        DocumentNumber.setBounds(450, 170, 220, 30);

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Miasto:");
        jLabel5.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel5.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel5.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel5);
        jLabel5.setBounds(370, 210, 50, 14);

        City.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CityActionPerformed(evt);
            }
        });
        Register.add(City);
        City.setBounds(450, 200, 220, 30);

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Państwo:");
        jLabel6.setMaximumSize(new java.awt.Dimension(29, 14));
        jLabel6.setMinimumSize(new java.awt.Dimension(29, 14));
        jLabel6.setPreferredSize(new java.awt.Dimension(29, 14));
        Register.add(jLabel6);
        jLabel6.setBounds(370, 240, 60, 14);

        Country.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CountryActionPerformed(evt);
            }
        });
        Register.add(Country);
        Country.setBounds(450, 230, 220, 30);

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Login:");
        Register.add(jLabel7);
        jLabel7.setBounds(370, 60, 50, 14);

        Street.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StreetActionPerformed(evt);
            }
        });
        Register.add(Street);
        Street.setBounds(450, 260, 220, 30);

        BackButton.setText("Powrót");
        BackButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackButtonActionPerformed(evt);
            }
        });
        Register.add(BackButton);
        BackButton.setBounds(490, 300, 80, 23);

        RegisterButton.setText("Załóż konto");
        RegisterButton.setMaximumSize(new java.awt.Dimension(67, 23));
        RegisterButton.setMinimumSize(new java.awt.Dimension(67, 23));
        RegisterButton.setPreferredSize(new java.awt.Dimension(67, 23));
        RegisterButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegisterButtonActionPerformed(evt);
            }
        });
        Register.add(RegisterButton);
        RegisterButton.setBounds(570, 300, 100, 23);

        RegisterBackgroundImage1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/register.jpg"))); // NOI18N
        RegisterBackgroundImage1.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        Register.add(RegisterBackgroundImage1);
        RegisterBackgroundImage1.setBounds(0, 0, 1220, 890);

        getContentPane().add(Register, "register");

        CashierPanel.setPreferredSize(new java.awt.Dimension(700, 700));
        CashierPanel.setLayout(new java.awt.CardLayout());

        MainPanel.setLayout(null);

        UserLogoutButton1.setText("Wyloguj");
        UserLogoutButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        UserLogoutButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        UserLogoutButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        UserLogoutButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutButton1ActionPerformed(evt);
            }
        });
        MainPanel.add(UserLogoutButton1);
        UserLogoutButton1.setBounds(580, 10, 80, 23);

        ContactButton1.setText("Założ konto klienta");
        ContactButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        ContactButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        ContactButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        MainPanel.add(ContactButton1);
        ContactButton1.setBounds(20, 130, 140, 23);

        SlopeTrafficButton1.setText("Natężenie stoku");
        SlopeTrafficButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        SlopeTrafficButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        SlopeTrafficButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        MainPanel.add(SlopeTrafficButton1);
        SlopeTrafficButton1.setBounds(20, 160, 140, 23);

        ClientModeButton1.setText("Tryb klienta");
        ClientModeButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientModeButton1ActionPerformed(evt);
            }
        });
        MainPanel.add(ClientModeButton1);
        ClientModeButton1.setBounds(480, 10, 100, 23);

        jTextField1.setText("szukaj klienta...");
        MainPanel.add(jTextField1);
        jTextField1.setBounds(190, 210, 200, 40);

        jButton3.setText("Anuluj");
        MainPanel.add(jButton3);
        jButton3.setBounds(620, 210, 70, 40);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        MainPanel.add(jScrollPane1);
        jScrollPane1.setBounds(190, 260, 280, 240);

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Wybrany użytkownik: brak");
        MainPanel.add(jLabel13);
        jLabel13.setBounds(190, 140, 490, 50);

        ContactButton3.setText("Kontakt");
        ContactButton3.setMaximumSize(new java.awt.Dimension(67, 23));
        ContactButton3.setMinimumSize(new java.awt.Dimension(67, 23));
        ContactButton3.setPreferredSize(new java.awt.Dimension(67, 23));
        MainPanel.add(ContactButton3);
        ContactButton3.setBounds(20, 190, 140, 23);

        jButton5.setText("Szukaj");
        MainPanel.add(jButton5);
        jButton5.setBounds(400, 210, 70, 40);

        jTextField2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField2.setText("Zeskanowano pomyślnie!");
        MainPanel.add(jTextField2);
        jTextField2.setBounds(510, 260, 180, 70);

        jButton4.setText("Skanuj kartę");
        MainPanel.add(jButton4);
        jButton4.setBounds(510, 210, 100, 40);

        UserBackgroundLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/universalBackground.jpg"))); // NOI18N
        MainPanel.add(UserBackgroundLabel1);
        UserBackgroundLabel1.setBounds(0, 0, 700, 700);

        CashierPanel.add(MainPanel, "MainPanel");

        ClientCardsPanel.setLayout(null);

        UserLogoutButton4.setText("Wyloguj");
        UserLogoutButton4.setMaximumSize(new java.awt.Dimension(67, 23));
        UserLogoutButton4.setMinimumSize(new java.awt.Dimension(67, 23));
        UserLogoutButton4.setPreferredSize(new java.awt.Dimension(67, 23));
        UserLogoutButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutButton4ActionPerformed(evt);
            }
        });
        ClientCardsPanel.add(UserLogoutButton4);
        UserLogoutButton4.setBounds(580, 10, 80, 23);

        AvailablePointsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        AvailablePointsLabel1.setText("Nieprzydzielone punkty:");
        AvailablePointsLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        AvailablePointsLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        AvailablePointsLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientCardsPanel.add(AvailablePointsLabel1);
        AvailablePointsLabel1.setBounds(200, 150, 130, 14);

        IDLabel1.setForeground(new java.awt.Color(255, 255, 255));
        IDLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDLabel1.setText("ID");
        IDLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        IDLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        IDLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientCardsPanel.add(IDLabel1);
        IDLabel1.setBounds(180, 190, 50, 14);

        ActivationDateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ActivationDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActivationDateLabel1.setText("Data aktywacji");
        ActivationDateLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        ActivationDateLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        ActivationDateLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientCardsPanel.add(ActivationDateLabel1);
        ActivationDateLabel1.setBounds(240, 190, 80, 14);

        ExpirationDateLabel1.setForeground(new java.awt.Color(255, 255, 255));
        ExpirationDateLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExpirationDateLabel1.setText("Data ważności");
        ExpirationDateLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        ExpirationDateLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        ExpirationDateLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientCardsPanel.add(ExpirationDateLabel1);
        ExpirationDateLabel1.setBounds(330, 190, 80, 14);

        PointsLabel1.setForeground(new java.awt.Color(255, 255, 255));
        PointsLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PointsLabel1.setText("Punkty");
        PointsLabel1.setMaximumSize(new java.awt.Dimension(29, 14));
        PointsLabel1.setMinimumSize(new java.awt.Dimension(29, 14));
        PointsLabel1.setPreferredSize(new java.awt.Dimension(29, 14));
        ClientCardsPanel.add(PointsLabel1);
        PointsLabel1.setBounds(420, 190, 50, 14);

        AvailablePointsTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AvailablePointsTextField1.setEnabled(false);
        ClientCardsPanel.add(AvailablePointsTextField1);
        AvailablePointsTextField1.setBounds(330, 150, 50, 20);

        IDTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDTextField1.setEnabled(false);
        ClientCardsPanel.add(IDTextField1);
        IDTextField1.setBounds(180, 210, 50, 20);

        ActivationDateTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActivationDateTextField1.setEnabled(false);
        ClientCardsPanel.add(ActivationDateTextField1);
        ActivationDateTextField1.setBounds(240, 210, 80, 20);

        ExpirationDateTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ExpirationDateTextField1.setEnabled(false);
        ClientCardsPanel.add(ExpirationDateTextField1);
        ExpirationDateTextField1.setBounds(330, 210, 80, 20);

        PointsTextField1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ClientCardsPanel.add(PointsTextField1);
        PointsTextField1.setBounds(420, 210, 50, 20);

        AddPointsButton1.setText("+");
        AddPointsButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        AddPointsButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        AddPointsButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientCardsPanel.add(AddPointsButton1);
        AddPointsButton1.setBounds(470, 210, 40, 20);

        SubtractPointsButton1.setText("-");
        SubtractPointsButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        SubtractPointsButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        SubtractPointsButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientCardsPanel.add(SubtractPointsButton1);
        SubtractPointsButton1.setBounds(510, 210, 40, 20);

        AddCardButton1.setText("Dodaj kartę");
        AddCardButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        AddCardButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        AddCardButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientCardsPanel.add(AddCardButton1);
        AddCardButton1.setBounds(560, 150, 100, 23);

        RemoveCardButton1.setText("Wydaj");
        RemoveCardButton1.setMaximumSize(new java.awt.Dimension(67, 23));
        RemoveCardButton1.setMinimumSize(new java.awt.Dimension(67, 23));
        RemoveCardButton1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientCardsPanel.add(RemoveCardButton1);
        RemoveCardButton1.setBounds(620, 210, 70, 23);

        CashierMenuButton1.setText("Menu Kasjera");
        CashierMenuButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierMenuButton1ActionPerformed(evt);
            }
        });
        ClientCardsPanel.add(CashierMenuButton1);
        CashierMenuButton1.setBounds(480, 10, 100, 23);

        ClientCards.setText("Karty Klienta");
        ClientCards.setActionCommand("Karty");
        ClientCards.setMaximumSize(new java.awt.Dimension(67, 23));
        ClientCards.setMinimumSize(new java.awt.Dimension(67, 23));
        ClientCards.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientCardsPanel.add(ClientCards);
        ClientCards.setBounds(30, 130, 110, 23);

        ClientAccount.setText("Dane Klienta");
        ClientAccount.setActionCommand("Karty");
        ClientAccount.setMaximumSize(new java.awt.Dimension(67, 23));
        ClientAccount.setMinimumSize(new java.awt.Dimension(67, 23));
        ClientAccount.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientAccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientAccountActionPerformed(evt);
            }
        });
        ClientCardsPanel.add(ClientAccount);
        ClientAccount.setBounds(30, 160, 110, 23);

        RemoveCardButton2.setText("Usuń");
        RemoveCardButton2.setMaximumSize(new java.awt.Dimension(67, 23));
        RemoveCardButton2.setMinimumSize(new java.awt.Dimension(67, 23));
        RemoveCardButton2.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientCardsPanel.add(RemoveCardButton2);
        RemoveCardButton2.setBounds(560, 210, 60, 23);

        jTextField3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField3.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField3.setText("Obsługa klienta: Nick");
        ClientCardsPanel.add(jTextField3);
        jTextField3.setBounds(170, 60, 510, 60);

        UserBackgroundLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clientPage.jpg"))); // NOI18N
        ClientCardsPanel.add(UserBackgroundLabel3);
        UserBackgroundLabel3.setBounds(0, 0, 700, 700);

        CashierPanel.add(ClientCardsPanel, "ClientCardsPanel");

        ClientAccountPanel.setMaximumSize(new java.awt.Dimension(700, 700));
        ClientAccountPanel.setMinimumSize(new java.awt.Dimension(700, 700));
        ClientAccountPanel.setName(""); // NOI18N
        ClientAccountPanel.setLayout(null);

        UserMyAccountButton3.setText("Tryb Kasjera");
        UserMyAccountButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMyAccountButton3ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(UserMyAccountButton3);
        UserMyAccountButton3.setBounds(490, 20, 110, 23);

        UserLogoutButton3.setText("Wyloguj");
        UserLogoutButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutButton3ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(UserLogoutButton3);
        UserLogoutButton3.setBounds(600, 20, 80, 23);

        MyAccountLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        MyAccountLabel1.setText("Konto klienta");
        ClientAccountPanel.add(MyAccountLabel1);
        MyAccountLabel1.setBounds(320, 150, 270, 30);

        EditLoginLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EditLoginLabel1.setText("Login");
        ClientAccountPanel.add(EditLoginLabel1);
        EditLoginLabel1.setBounds(200, 240, 80, 30);

        EditPasswordLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        EditPasswordLabel1.setText("Hasło");
        ClientAccountPanel.add(EditPasswordLabel1);
        EditPasswordLabel1.setBounds(200, 270, 80, 30);
        ClientAccountPanel.add(LoginEditTextfield1);
        LoginEditTextfield1.setBounds(300, 240, 180, 30);

        PasswordEditTextfield1.setEditable(false);
        PasswordEditTextfield1.setText("*****");
        ClientAccountPanel.add(PasswordEditTextfield1);
        PasswordEditTextfield1.setBounds(300, 270, 180, 30);
        ClientAccountPanel.add(NameEditTextfield1);
        NameEditTextfield1.setBounds(300, 300, 180, 30);
        ClientAccountPanel.add(SurnameEditTextfield1);
        SurnameEditTextfield1.setBounds(300, 330, 180, 30);

        NameEditLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        NameEditLabel1.setText("Imię");
        ClientAccountPanel.add(NameEditLabel1);
        NameEditLabel1.setBounds(200, 300, 80, 30);

        SurnameEditLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        SurnameEditLabel1.setText("Nazwisko");
        ClientAccountPanel.add(SurnameEditLabel1);
        SurnameEditLabel1.setBounds(200, 330, 80, 30);

        IDEditLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        IDEditLabel1.setText("ID");
        ClientAccountPanel.add(IDEditLabel1);
        IDEditLabel1.setBounds(200, 210, 80, 30);

        IDEditTextfield1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEditTextfield1ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(IDEditTextfield1);
        IDEditTextfield1.setBounds(300, 210, 180, 30);
        ClientAccountPanel.add(StreetEditTextfield1);
        StreetEditTextfield1.setBounds(300, 390, 180, 30);
        ClientAccountPanel.add(CityEditTextfield1);
        CityEditTextfield1.setBounds(300, 420, 180, 30);
        ClientAccountPanel.add(CountryEditTextfield1);
        CountryEditTextfield1.setBounds(300, 450, 180, 30);

        StreetEditLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        StreetEditLabel1.setText("Ulica");
        ClientAccountPanel.add(StreetEditLabel1);
        StreetEditLabel1.setBounds(200, 390, 80, 30);

        CityEditLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CityEditLabel1.setText("Miasto");
        ClientAccountPanel.add(CityEditLabel1);
        CityEditLabel1.setBounds(200, 420, 80, 30);

        CountryEditLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        CountryEditLabel1.setText("Kraj");
        ClientAccountPanel.add(CountryEditLabel1);
        CountryEditLabel1.setBounds(200, 450, 80, 30);

        EditDetailsButton1.setText("Edytuj Dane");
        EditDetailsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDetailsButton1ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(EditDetailsButton1);
        EditDetailsButton1.setBounds(300, 500, 180, 23);

        SaveDetailsButton1.setText("Zapisz");
        SaveDetailsButton1.setEnabled(false);
        SaveDetailsButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDetailsButton1ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(SaveDetailsButton1);
        SaveDetailsButton1.setBounds(400, 530, 80, 23);

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("Nr dokumentu");
        ClientAccountPanel.add(jLabel11);
        jLabel11.setBounds(200, 360, 100, 30);

        CancelButton1.setText("Anuluj");
        CancelButton1.setEnabled(false);
        CancelButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButton1ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(CancelButton1);
        CancelButton1.setBounds(300, 530, 73, 23);

        EditMessageLabel1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        ClientAccountPanel.add(EditMessageLabel1);
        EditMessageLabel1.setBounds(300, 560, 180, 20);
        ClientAccountPanel.add(DocumentEditTextfield1);
        DocumentEditTextfield1.setBounds(300, 360, 180, 30);

        ClientCards1.setText("Karty Klienta");
        ClientCards1.setActionCommand("Karty");
        ClientCards1.setMaximumSize(new java.awt.Dimension(67, 23));
        ClientCards1.setMinimumSize(new java.awt.Dimension(67, 23));
        ClientCards1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientAccountPanel.add(ClientCards1);
        ClientCards1.setBounds(30, 130, 110, 23);

        ClientAccount1.setText("Dane Klienta");
        ClientAccount1.setActionCommand("Karty");
        ClientAccount1.setMaximumSize(new java.awt.Dimension(67, 23));
        ClientAccount1.setMinimumSize(new java.awt.Dimension(67, 23));
        ClientAccount1.setPreferredSize(new java.awt.Dimension(67, 23));
        ClientAccount1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientAccount1ActionPerformed(evt);
            }
        });
        ClientAccountPanel.add(ClientAccount1);
        ClientAccount1.setBounds(30, 160, 110, 23);

        jTextField4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTextField4.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jTextField4.setText("Obsługa klienta: Nick");
        ClientAccountPanel.add(jTextField4);
        jTextField4.setBounds(170, 60, 510, 60);

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/myAccountPage.jpg"))); // NOI18N
        jLabel12.setText("jLabel9");
        ClientAccountPanel.add(jLabel12);
        jLabel12.setBounds(0, 0, 700, 700);

        CashierPanel.add(ClientAccountPanel, "ClientAccountPanel");

        getContentPane().add(CashierPanel, "CashierPanel");

        AdminMainPanel.setLayout(null);

        SlopeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        SlopeButton.setText("Stok");
        AdminMainPanel.add(SlopeButton);
        SlopeButton.setBounds(180, 370, 160, 80);

        PriceListButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        PriceListButton.setText("Cennik");
        PriceListButton.setToolTipText("");
        AdminMainPanel.add(PriceListButton);
        PriceListButton.setBounds(350, 280, 160, 80);

        CashierModeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        CashierModeButton.setText("Tryb kasjera");
        CashierModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CashierModeButtonActionPerformed(evt);
            }
        });
        AdminMainPanel.add(CashierModeButton);
        CashierModeButton.setBounds(180, 460, 160, 80);

        GatesButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        GatesButton.setText("Bramki");
        AdminMainPanel.add(GatesButton);
        GatesButton.setBounds(350, 370, 160, 80);

        ClientModeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ClientModeButton.setText("Tryb klienta");
        ClientModeButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ClientModeButtonActionPerformed(evt);
            }
        });
        AdminMainPanel.add(ClientModeButton);
        ClientModeButton.setBounds(350, 460, 160, 80);

        UsersButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        UsersButton.setText("Użytkownicy");
        UsersButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsersButtonActionPerformed(evt);
            }
        });
        AdminMainPanel.add(UsersButton);
        UsersButton.setBounds(180, 280, 160, 80);

        AdminLogoutButton.setText("Wyloguj");
        AdminLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminLogoutButtonActionPerformed(evt);
            }
        });
        AdminMainPanel.add(AdminLogoutButton);
        AdminLogoutButton.setBounds(600, 40, 80, 23);

        AdminMyAccountButton.setText("Moje konto");
        AdminMyAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AdminMyAccountButtonActionPerformed(evt);
            }
        });
        AdminMainPanel.add(AdminMyAccountButton);
        AdminMyAccountButton.setBounds(510, 40, 90, 23);

        AdminBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/skibackgroundAdmin.jpg"))); // NOI18N
        AdminBackgroundLabel.setVerticalAlignment(javax.swing.SwingConstants.TOP);
        AdminMainPanel.add(AdminBackgroundLabel);
        AdminBackgroundLabel.setBounds(0, 0, 1220, 890);

        getContentPane().add(AdminMainPanel, "adminPanelMain");

        UserManagmenAdmintPanel.setLayout(null);

        UpdateUser.setText("Aktualizuj");
        UpdateUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UpdateUserActionPerformed(evt);
            }
        });
        UserManagmenAdmintPanel.add(UpdateUser);
        UpdateUser.setBounds(260, 500, 80, 23);

        RemoveUser.setText("Usuń");
        RemoveUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RemoveUserActionPerformed(evt);
            }
        });
        UserManagmenAdmintPanel.add(RemoveUser);
        RemoveUser.setBounds(180, 500, 80, 23);

        Back.setText("Wstecz");
        Back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BackActionPerformed(evt);
            }
        });
        UserManagmenAdmintPanel.add(Back);
        Back.setBounds(110, 560, 80, 23);

        jButton1.setText("Moje konto");
        UserManagmenAdmintPanel.add(jButton1);
        jButton1.setBounds(510, 40, 90, 23);

        jButton2.setText("Wyloguj");
        UserManagmenAdmintPanel.add(jButton2);
        jButton2.setBounds(600, 40, 80, 23);

        FindLoginTextField.setMaximumSize(new java.awt.Dimension(6, 22));
        FindLoginTextField.setMinimumSize(new java.awt.Dimension(6, 22));
        FindLoginTextField.setPreferredSize(new java.awt.Dimension(59, 22));
        FindLoginTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindLoginTextFieldActionPerformed(evt);
            }
        });
        UserManagmenAdmintPanel.add(FindLoginTextField);
        FindLoginTextField.setBounds(180, 310, 142, 23);

        FindUser.setText("Szukaj");
        FindUser.setMaximumSize(new java.awt.Dimension(67, 23));
        FindUser.setMinimumSize(new java.awt.Dimension(67, 23));
        FindUser.setPreferredSize(new java.awt.Dimension(67, 23));
        FindUser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FindUserActionPerformed(evt);
            }
        });
        UserManagmenAdmintPanel.add(FindUser);
        FindUser.setBounds(320, 310, 80, 23);

        FindResultLabel.setForeground(new java.awt.Color(255, 255, 255));
        UserManagmenAdmintPanel.add(FindResultLabel);
        FindResultLabel.setBounds(180, 340, 140, 20);

        UserRoleChooseGroup.add(UserRadio);
        UserRadio.setForeground(new java.awt.Color(255, 255, 255));
        UserRadio.setText("User");
        UserRadio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserRadioActionPerformed(evt);
            }
        });
        UserManagmenAdmintPanel.add(UserRadio);
        UserRadio.setBounds(180, 443, 80, 30);

        UserRoleChooseGroup.add(CashierRadio);
        CashierRadio.setForeground(new java.awt.Color(255, 255, 255));
        CashierRadio.setText("Cashier");
        UserManagmenAdmintPanel.add(CashierRadio);
        CashierRadio.setBounds(180, 403, 80, 30);

        UserRoleChooseGroup.add(AdminRadio);
        AdminRadio.setForeground(new java.awt.Color(255, 255, 255));
        AdminRadio.setText("Admin");
        UserManagmenAdmintPanel.add(AdminRadio);
        AdminRadio.setBounds(180, 363, 80, 30);
        UserManagmenAdmintPanel.add(UpdateResultLabel);
        UpdateResultLabel.setBounds(180, 510, 80, 20);

        UserManagePanelBackgroud.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/skibackgroundAdmin.jpg"))); // NOI18N
        UserManagePanelBackgroud.setText("jLabel9");
        UserManagmenAdmintPanel.add(UserManagePanelBackgroud);
        UserManagePanelBackgroud.setBounds(0, 0, 700, 700);

        getContentPane().add(UserManagmenAdmintPanel, "userManagmentAdminPanel");

        UserMainPanel.setPreferredSize(new java.awt.Dimension(700, 700));
        UserMainPanel.setLayout(null);

        UserMyAccountButton.setText("Moje konto");
        UserMyAccountButton.setMaximumSize(new java.awt.Dimension(67, 23));
        UserMyAccountButton.setMinimumSize(new java.awt.Dimension(67, 23));
        UserMyAccountButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMyAccountButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMyAccountButtonActionPerformed(evt);
            }
        });
        UserMainPanel.add(UserMyAccountButton);
        UserMyAccountButton.setBounds(480, 10, 100, 23);

        UserLogoutButton.setText("Wyloguj");
        UserLogoutButton.setMaximumSize(new java.awt.Dimension(67, 23));
        UserLogoutButton.setMinimumSize(new java.awt.Dimension(67, 23));
        UserLogoutButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserLogoutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutButtonActionPerformed(evt);
            }
        });
        UserMainPanel.add(UserLogoutButton);
        UserLogoutButton.setBounds(580, 10, 80, 23);

        ContactButton.setText("Kontakt");
        ContactButton.setMaximumSize(new java.awt.Dimension(67, 23));
        ContactButton.setMinimumSize(new java.awt.Dimension(67, 23));
        ContactButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(ContactButton);
        ContactButton.setBounds(20, 130, 125, 23);

        MyCardsButton.setText("Moje karty");
        MyCardsButton.setMaximumSize(new java.awt.Dimension(67, 23));
        MyCardsButton.setMinimumSize(new java.awt.Dimension(67, 23));
        MyCardsButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(MyCardsButton);
        MyCardsButton.setBounds(20, 70, 125, 23);

        SlopeTrafficButton.setText("Natężenie stoku");
        SlopeTrafficButton.setMaximumSize(new java.awt.Dimension(67, 23));
        SlopeTrafficButton.setMinimumSize(new java.awt.Dimension(67, 23));
        SlopeTrafficButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(SlopeTrafficButton);
        SlopeTrafficButton.setBounds(20, 100, 125, 23);

        AvailablePointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        AvailablePointsLabel.setText("Nieprzydzielone punkty:");
        AvailablePointsLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        AvailablePointsLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        AvailablePointsLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        UserMainPanel.add(AvailablePointsLabel);
        AvailablePointsLabel.setBounds(200, 150, 130, 14);

        IDLabel.setForeground(new java.awt.Color(255, 255, 255));
        IDLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        IDLabel.setText("ID");
        IDLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        IDLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        IDLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        UserMainPanel.add(IDLabel);
        IDLabel.setBounds(180, 190, 50, 14);

        ActivationDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ActivationDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ActivationDateLabel.setText("Data aktywacji");
        ActivationDateLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        ActivationDateLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        ActivationDateLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        UserMainPanel.add(ActivationDateLabel);
        ActivationDateLabel.setBounds(240, 190, 80, 14);

        ExpirationDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        ExpirationDateLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ExpirationDateLabel.setText("Data ważności");
        ExpirationDateLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        ExpirationDateLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        ExpirationDateLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        UserMainPanel.add(ExpirationDateLabel);
        ExpirationDateLabel.setBounds(330, 190, 80, 14);

        PointsLabel.setForeground(new java.awt.Color(255, 255, 255));
        PointsLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        PointsLabel.setText("Punkty");
        PointsLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        PointsLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        PointsLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        UserMainPanel.add(PointsLabel);
        PointsLabel.setBounds(420, 190, 50, 14);

        AvailablePointsTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        AvailablePointsTextField.setEnabled(false);
        UserMainPanel.add(AvailablePointsTextField);
        AvailablePointsTextField.setBounds(330, 150, 50, 20);

        IDTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        IDTextField.setEnabled(false);
        UserMainPanel.add(IDTextField);
        IDTextField.setBounds(180, 210, 50, 20);

        ActivationDateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ActivationDateTextField.setEnabled(false);
        UserMainPanel.add(ActivationDateTextField);
        ActivationDateTextField.setBounds(240, 210, 80, 20);

        ExpirationDateTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        ExpirationDateTextField.setEnabled(false);
        UserMainPanel.add(ExpirationDateTextField);
        ExpirationDateTextField.setBounds(330, 210, 80, 20);

        PointsTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        UserMainPanel.add(PointsTextField);
        PointsTextField.setBounds(420, 210, 50, 20);

        AddPointsButton.setText("+");
        AddPointsButton.setMaximumSize(new java.awt.Dimension(67, 23));
        AddPointsButton.setMinimumSize(new java.awt.Dimension(67, 23));
        AddPointsButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(AddPointsButton);
        AddPointsButton.setBounds(470, 210, 40, 20);

        SubtractPointsButton.setText("-");
        SubtractPointsButton.setMaximumSize(new java.awt.Dimension(67, 23));
        SubtractPointsButton.setMinimumSize(new java.awt.Dimension(67, 23));
        SubtractPointsButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(SubtractPointsButton);
        SubtractPointsButton.setBounds(510, 210, 40, 20);

        AddCardButton.setText("Dodaj kartę");
        AddCardButton.setMaximumSize(new java.awt.Dimension(67, 23));
        AddCardButton.setMinimumSize(new java.awt.Dimension(67, 23));
        AddCardButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(AddCardButton);
        AddCardButton.setBounds(560, 150, 100, 23);

        RemoveCardButton.setText("Usuń kartę");
        RemoveCardButton.setMaximumSize(new java.awt.Dimension(67, 23));
        RemoveCardButton.setMinimumSize(new java.awt.Dimension(67, 23));
        RemoveCardButton.setPreferredSize(new java.awt.Dimension(67, 23));
        UserMainPanel.add(RemoveCardButton);
        RemoveCardButton.setBounds(560, 210, 100, 23);

        UserBackgroundLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/clientPage.jpg"))); // NOI18N
        UserMainPanel.add(UserBackgroundLabel);
        UserBackgroundLabel.setBounds(0, 0, 700, 700);

        getContentPane().add(UserMainPanel, "UserMainPanel");

        MyAccountPanel.setMaximumSize(new java.awt.Dimension(700, 700));
        MyAccountPanel.setMinimumSize(new java.awt.Dimension(700, 700));
        MyAccountPanel.setName(""); // NOI18N
        MyAccountPanel.setLayout(null);

        UserMyAccountButton2.setText("Moje Konto");
        UserMyAccountButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserMyAccountButton2ActionPerformed(evt);
            }
        });
        MyAccountPanel.add(UserMyAccountButton2);
        UserMyAccountButton2.setBounds(480, 10, 100, 23);

        UserLogoutButton2.setText("Wyloguj");
        UserLogoutButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UserLogoutButton2ActionPerformed(evt);
            }
        });
        MyAccountPanel.add(UserLogoutButton2);
        UserLogoutButton2.setBounds(580, 10, 80, 23);

        EditLoginLabel.setForeground(new java.awt.Color(255, 255, 255));
        EditLoginLabel.setText("Login:");
        MyAccountPanel.add(EditLoginLabel);
        EditLoginLabel.setBounds(330, 200, 50, 14);

        EditPasswordLabel.setForeground(new java.awt.Color(255, 255, 255));
        EditPasswordLabel.setText("Hasło:");
        EditPasswordLabel.setMaximumSize(new java.awt.Dimension(29, 14));
        EditPasswordLabel.setMinimumSize(new java.awt.Dimension(29, 14));
        EditPasswordLabel.setPreferredSize(new java.awt.Dimension(29, 14));
        MyAccountPanel.add(EditPasswordLabel);
        EditPasswordLabel.setBounds(330, 230, 50, 17);
        MyAccountPanel.add(LoginEditTextfield);
        LoginEditTextfield.setBounds(420, 190, 220, 30);

        PasswordEditTextfield.setEditable(false);
        PasswordEditTextfield.setText("*****");
        MyAccountPanel.add(PasswordEditTextfield);
        PasswordEditTextfield.setBounds(420, 220, 220, 30);
        MyAccountPanel.add(NameEditTextfield);
        NameEditTextfield.setBounds(420, 250, 220, 30);
        MyAccountPanel.add(SurnameEditTextfield);
        SurnameEditTextfield.setBounds(420, 280, 220, 30);

        NameEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        NameEditLabel.setText("Imię:");
        MyAccountPanel.add(NameEditLabel);
        NameEditLabel.setBounds(330, 260, 50, 14);

        SurnameEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        SurnameEditLabel.setText("Nazwisko:");
        MyAccountPanel.add(SurnameEditLabel);
        SurnameEditLabel.setBounds(330, 290, 80, 14);

        IDEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        IDEditLabel.setText("ID:");
        MyAccountPanel.add(IDEditLabel);
        IDEditLabel.setBounds(330, 170, 50, 14);

        IDEditTextfield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                IDEditTextfieldActionPerformed(evt);
            }
        });
        MyAccountPanel.add(IDEditTextfield);
        IDEditTextfield.setBounds(420, 160, 220, 30);
        MyAccountPanel.add(StreetEditTextfield);
        StreetEditTextfield.setBounds(420, 340, 220, 30);
        MyAccountPanel.add(CityEditTextfield);
        CityEditTextfield.setBounds(420, 370, 220, 30);
        MyAccountPanel.add(CountryEditTextfield);
        CountryEditTextfield.setBounds(420, 400, 220, 30);

        StreetEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        StreetEditLabel.setText("Ulica:");
        MyAccountPanel.add(StreetEditLabel);
        StreetEditLabel.setBounds(330, 350, 50, 14);

        CityEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        CityEditLabel.setText("Miasto:");
        MyAccountPanel.add(CityEditLabel);
        CityEditLabel.setBounds(330, 380, 50, 14);

        CountryEditLabel.setForeground(new java.awt.Color(255, 255, 255));
        CountryEditLabel.setText("Kraj:");
        MyAccountPanel.add(CountryEditLabel);
        CountryEditLabel.setBounds(330, 410, 50, 14);

        EditDetailsButton.setText("Edytuj Dane");
        EditDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditDetailsButtonActionPerformed(evt);
            }
        });
        MyAccountPanel.add(EditDetailsButton);
        EditDetailsButton.setBounds(420, 440, 220, 23);

        SaveDetailsButton.setText("Zapisz");
        SaveDetailsButton.setEnabled(false);
        SaveDetailsButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveDetailsButtonActionPerformed(evt);
            }
        });
        MyAccountPanel.add(SaveDetailsButton);
        SaveDetailsButton.setBounds(560, 470, 80, 23);

        MyCardsButton2.setText("Moje karty");
        MyCardsButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MyCardsButton2ActionPerformed(evt);
            }
        });
        MyAccountPanel.add(MyCardsButton2);
        MyCardsButton2.setBounds(20, 70, 125, 23);

        SlopeTrafficButton2.setText("Natężenie stoku");
        MyAccountPanel.add(SlopeTrafficButton2);
        SlopeTrafficButton2.setBounds(20, 100, 125, 23);

        ContactButton2.setText("Kontakt");
        MyAccountPanel.add(ContactButton2);
        ContactButton2.setBounds(20, 130, 125, 23);

        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Nr dokumentu:");
        MyAccountPanel.add(jLabel10);
        jLabel10.setBounds(330, 320, 90, 14);

        CancelButton.setText("Anuluj");
        CancelButton.setEnabled(false);
        CancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CancelButtonActionPerformed(evt);
            }
        });
        MyAccountPanel.add(CancelButton);
        CancelButton.setBounds(490, 470, 73, 23);

        EditMessageLabel.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        MyAccountPanel.add(EditMessageLabel);
        EditMessageLabel.setBounds(300, 560, 180, 20);
        MyAccountPanel.add(DocumentEditTextfield);
        DocumentEditTextfield.setBounds(420, 310, 220, 30);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/myacoount.jpg"))); // NOI18N
        jLabel9.setText("jLabel9");
        MyAccountPanel.add(jLabel9);
        jLabel9.setBounds(0, 0, 700, 700);

        getContentPane().add(MyAccountPanel, "myAccountPanel");
        MyAccountPanel.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTextFieldActionPerformed

    private void PasswordTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordTextFieldActionPerformed

    private void CreateAccountLinkMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CreateAccountLinkMouseClicked
        // TODO add your handling code here:
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        loginPaneLayout.show(getContentPane(), "register");
        RegisterMessageLabel.setText("");
    }//GEN-LAST:event_CreateAccountLinkMouseClicked

    private void LoginTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_LoginTextField1ActionPerformed

    private void PasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_PasswordActionPerformed

    private void NameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_NameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_NameActionPerformed

    private void SurnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SurnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SurnameActionPerformed

    private void DocumentNumberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DocumentNumberActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DocumentNumberActionPerformed

    private void LoginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LoginButtonActionPerformed
        //TestClass.test();        // TODO add your handling code here:
        StringBuilder viewPanel = new StringBuilder();
        if (LoginController.logIn(LoginTextField.getText(), new String(PasswordTextField.getPassword()), viewPanel, loginStatusMessage)){
            MessageLabel.setText("");
            CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
            loginPaneLayout.show(getContentPane(), viewPanel.toString());
            //TODO change view x----DDDDDDDD
        } else
        {
            MessageLabel.setText("Błędny login i/lub hasło");//TODO error message, wrong login and/or password
            Password.setText("");
        }
    }//GEN-LAST:event_LoginButtonActionPerformed

    private void CityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CityActionPerformed

    private void CountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CountryActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CountryActionPerformed

    private void StreetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StreetActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_StreetActionPerformed

    private void BackButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackButtonActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        loginPaneLayout.show(getContentPane(), "login");
        MessageLabel.setText("");
    }//GEN-LAST:event_BackButtonActionPerformed

    private void RegisterButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegisterButtonActionPerformed
        RegistrationController regController = new RegistrationController();
        Boolean isSuccess = regController.register(Name.getText(), Surname.getText(), City.getText(), Country.getText(), Street.getText(), LoginTextField1.getText(), new String(Password.getPassword()), DocumentNumber.getText());
        if (isSuccess) {
            MessageLabel.setText("");
            CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
            loginPaneLayout.show(getContentPane(), "login");
        }else{
            RegisterMessageLabel.setText( "Wybierz inny login" );
            LoginTextField1.setText("");
            Password.setText("");
        }
    }//GEN-LAST:event_RegisterButtonActionPerformed

    private void UpdateUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UpdateUserActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }
        UserManagementAdminController controller = new UserManagementAdminController();
        String choosingRole = getSelectedButtonText(UserRoleChooseGroup);
        if (controller.exist(FindLoginTextField.getText())) {
            controller.updateUser(FindLoginTextField.getText(), choosingRole);
            UpdateResultLabel.setText("Updated!");
        }else{
                UpdateResultLabel.setText("User does not exist!");
        }
    }//GEN-LAST:event_UpdateUserActionPerformed

    private void RemoveUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RemoveUserActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }    
        UserManagementAdminController controller = new UserManagementAdminController();
        if (controller.removeUser(FindLoginTextField.getText())) {
            UpdateResultLabel.setText("Removed");
        }else{
            UpdateResultLabel.setText("User does not exist!");
        }
    }//GEN-LAST:event_RemoveUserActionPerformed

    private void BackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BackActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }
        loginPaneLayout.show(getContentPane(), "adminPanelMain");
    }//GEN-LAST:event_BackActionPerformed

    private void FindLoginTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindLoginTextFieldActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }
    }//GEN-LAST:event_FindLoginTextFieldActionPerformed

    private void FindUserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FindUserActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }    
        UserManagementAdminController controller = new UserManagementAdminController();
            
            if (controller.exist(FindLoginTextField.getText())) {
                FindResultLabel.setText("User exists!");
                String roleName = controller.getUserRole(FindLoginTextField.getText());

                if (roleName=="User") {
                   UserRoleChooseGroup.setSelected(UserRadio.getModel(), true);
                }else if (roleName.equals(RegistrationController.EmployeeTypes.Admin.toString())) {
                   UserRoleChooseGroup.setSelected(AdminRadio.getModel(), true);
                }else if (roleName.equals(RegistrationController.EmployeeTypes.Cashier.toString())) {
                   UserRoleChooseGroup.setSelected(CashierRadio.getModel(), true);
                }
            }else{
                UserRoleChooseGroup.clearSelection();
                FindResultLabel.setText("User does not exist!");
            }
            
    }//GEN-LAST:event_FindUserActionPerformed

    private String getSelectedButtonText(ButtonGroup buttonGroup) {
        for (Enumeration<AbstractButton> buttons = buttonGroup.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }

        return null;
    }
        
    private void UsersButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsersButtonActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        if( SessionController.IsUserLogged() ){
            loginPaneLayout.show(getContentPane(), "userManagmentAdminPanel");
        }
        else {
            ExitSession();
        }
    }//GEN-LAST:event_UsersButtonActionPerformed

    private void UserRadioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserRadioActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
        }
    }//GEN-LAST:event_UserRadioActionPerformed

    private void ClientModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientModeButtonActionPerformed
        MyCardsButton2ActionPerformed( evt );
    }//GEN-LAST:event_ClientModeButtonActionPerformed

    private void AdminLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminLogoutButtonActionPerformed
        SessionController.ResetSession();
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        loginPaneLayout.show(getContentPane(), "login");
        PasswordTextField.setText((""));
        LoginTextField.setText("");
    }//GEN-LAST:event_AdminLogoutButtonActionPerformed

    private void UserLogoutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutButtonActionPerformed
        AdminLogoutButtonActionPerformed( evt );
    }//GEN-LAST:event_UserLogoutButtonActionPerformed

    private void UserLogoutButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutButton2ActionPerformed
        UserLogoutButtonActionPerformed(evt);
    }//GEN-LAST:event_UserLogoutButton2ActionPerformed

    private void UserMyAccountButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMyAccountButton2ActionPerformed
        UserMyAccountButtonActionPerformed( evt );
    }//GEN-LAST:event_UserMyAccountButton2ActionPerformed

    private void MyCardsButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MyCardsButton2ActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        if( SessionController.IsUserLogged() ){
            loginPaneLayout.show(getContentPane(), "UserMainPanel");
        }
        else {
            ExitSession();
        }
    }//GEN-LAST:event_MyCardsButton2ActionPerformed

    private void UserMyAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMyAccountButtonActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        if( SessionController.IsUserLogged() ){
            SetAccountInfo();
            loginPaneLayout.show(getContentPane(), "myAccountPanel");
        }
        else {
            ExitSession();
        }
    }//GEN-LAST:event_UserMyAccountButtonActionPerformed

    private void SetAccountInfo(){
        Users user = MyAccountController.GetAccountDetails();
        if( user == null )
            return;
        IDEditTextfield.setEnabled(true);
        IDEditTextfield.setText(Integer.toString((user.getUserid())) );
        IDEditTextfield.setEnabled(false);
        LoginEditTextfield.setText(user.getLogin());
        LoginEditTextfield.setEditable(false);
        NameEditTextfield.setText(user.getName());
        NameEditTextfield.setEditable(false);
        SurnameEditTextfield.setText(user.getSurname());
        SurnameEditTextfield.setEditable(false);
        StreetEditTextfield.setText(user.getAddresses().getStreet());
        StreetEditTextfield.setEditable(false);
        CityEditTextfield.setText(user.getAddresses().getCity());
        CityEditTextfield.setEditable(false);
        CountryEditTextfield.setText(user.getAddresses().getCountry());
        CountryEditTextfield.setEditable(false);
        DocumentEditTextfield.setText(user.getAddresses().getCountry());
        DocumentEditTextfield.setEditable(false);
    }
    
    private void IDEditTextfieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEditTextfieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEditTextfieldActionPerformed

    private void SaveDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDetailsButtonActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }
        EditMessageLabel.setText( MyAccountController.UpdateAccountDetails( GetDataFromTextfields()) );
        PasswordEditTextfield.setEnabled(false);
        LoginEditTextfield.setEditable(false);
        NameEditTextfield.setEditable(false);
        SurnameEditTextfield.setEditable(false);
        StreetEditTextfield.setEditable(false);
        CityEditTextfield.setEditable(false);
        CountryEditTextfield.setEditable(false);
        SaveDetailsButton.setEnabled(false);
        CancelButton.setEnabled(false);
        DocumentEditTextfield.setEnabled(false);
    }//GEN-LAST:event_SaveDetailsButtonActionPerformed

    private Users GetDataFromTextfields(){
        Users user = new Users();
        Addresses address = new Addresses();
        user.setLogin(LoginEditTextfield.getText());
        user.setPassword(PasswordEditTextfield.getText());
        user.setName(NameEditTextfield.getText());
        user.setSurname(SurnameEditTextfield.getText());
        user.setDocumentnumber(DocumentEditTextfield.getText());
        address.setStreet(StreetEditTextfield.getText());
        address.setCity(CityEditTextfield.getText());
        address.setCountry(CountryEditTextfield.getText());
        user.setAddresses(address);
        return user;
    }
    private void EditDetailsButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDetailsButtonActionPerformed
        if( SessionController.IsUserLogged() ){
            LoginEditTextfield.setEditable(false);
            PasswordEditTextfield.setEditable(true);
            NameEditTextfield.setEditable(true);
            SurnameEditTextfield.setEditable(true);
            StreetEditTextfield.setEditable(true);
            CityEditTextfield.setEditable(true);
            CountryEditTextfield.setEditable(true);
            SaveDetailsButton.setEnabled(true);
            CancelButton.setEnabled(true);
            DocumentEditTextfield.setEnabled(true);
        }
        else {
            ExitSession();
        }
    }//GEN-LAST:event_EditDetailsButtonActionPerformed

    private void AdminMyAccountButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AdminMyAccountButtonActionPerformed
        UserMyAccountButtonActionPerformed( evt );
    }//GEN-LAST:event_AdminMyAccountButtonActionPerformed

    private void CancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButtonActionPerformed
        if( !SessionController.IsUserLogged() ){
            ExitSession();
            return;
        }
        SetAccountInfo();
        SaveDetailsButton.setEnabled(false);
        CancelButton.setEnabled(false);
    }//GEN-LAST:event_CancelButtonActionPerformed

    private void UserLogoutButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserLogoutButton1ActionPerformed

    private void ClientModeButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientModeButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientModeButton1ActionPerformed

    private void UserLogoutButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserLogoutButton4ActionPerformed

    private void CashierMenuButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierMenuButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CashierMenuButton1ActionPerformed

    private void UserMyAccountButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserMyAccountButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserMyAccountButton3ActionPerformed

    private void UserLogoutButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UserLogoutButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_UserLogoutButton3ActionPerformed

    private void IDEditTextfield1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_IDEditTextfield1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_IDEditTextfield1ActionPerformed

    private void EditDetailsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditDetailsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditDetailsButton1ActionPerformed

    private void SaveDetailsButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveDetailsButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SaveDetailsButton1ActionPerformed

    private void CancelButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CancelButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CancelButton1ActionPerformed

    private void ClientAccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientAccountActionPerformed
        //ClientAccountPanel
        
        //CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        
        if( SessionController.IsUserLogged() ){
            loginPaneLayout.show(getContentPane(), "ClientAccountPanel");
            System.out.print("Pokazuje Client Account");
        }
        else {
            ExitSession();
        }
    }//GEN-LAST:event_ClientAccountActionPerformed

    private void CashierModeButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CashierModeButtonActionPerformed
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        if( SessionController.IsUserLogged() ){
            loginPaneLayout.show(getContentPane(), "CashierPanel");
            System.out.print("Wyswietlam kasjera \n");
        }
        else {
            ExitSession();
        }
    }//GEN-LAST:event_CashierModeButtonActionPerformed

    private void ClientAccount1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ClientAccount1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ClientAccount1ActionPerformed

    private void ExitSession(){
        CardLayout loginPaneLayout = (CardLayout) getContentPane().getLayout();
        PasswordTextField.setText("");
        MessageLabel.setText("Sesja wygasła");
        loginPaneLayout.show(getContentPane(), "login");
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel ActionInfoLabel;
    private javax.swing.JLabel ActivationDateLabel;
    private javax.swing.JLabel ActivationDateLabel1;
    private javax.swing.JTextField ActivationDateTextField;
    private javax.swing.JTextField ActivationDateTextField1;
    private javax.swing.JButton AddCardButton;
    private javax.swing.JButton AddCardButton1;
    private javax.swing.JButton AddPointsButton;
    private javax.swing.JButton AddPointsButton1;
    private javax.swing.JLabel AdminBackgroundLabel;
    private javax.swing.JButton AdminLogoutButton;
    private javax.swing.JPanel AdminMainPanel;
    private javax.swing.JButton AdminMyAccountButton;
    private javax.swing.JRadioButton AdminRadio;
    private javax.swing.JLabel AvailablePointsLabel;
    private javax.swing.JLabel AvailablePointsLabel1;
    private javax.swing.JTextField AvailablePointsTextField;
    private javax.swing.JTextField AvailablePointsTextField1;
    private javax.swing.JButton Back;
    private javax.swing.JButton BackButton;
    private javax.swing.JLabel BackgroundImageLabel;
    private javax.swing.JButton CancelButton;
    private javax.swing.JButton CancelButton1;
    private javax.swing.JButton CashierMenuButton1;
    private javax.swing.JButton CashierModeButton;
    private javax.swing.JPanel CashierPanel;
    private javax.swing.JRadioButton CashierRadio;
    private javax.swing.JTextField City;
    private javax.swing.JLabel CityEditLabel;
    private javax.swing.JLabel CityEditLabel1;
    private javax.swing.JTextField CityEditTextfield;
    private javax.swing.JTextField CityEditTextfield1;
    private javax.swing.JButton ClientAccount;
    private javax.swing.JButton ClientAccount1;
    private javax.swing.JPanel ClientAccountPanel;
    private javax.swing.JButton ClientCards;
    private javax.swing.JButton ClientCards1;
    private javax.swing.JPanel ClientCardsPanel;
    private javax.swing.JButton ClientModeButton;
    private javax.swing.JButton ClientModeButton1;
    private javax.swing.JButton ContactButton;
    private javax.swing.JButton ContactButton1;
    private javax.swing.JButton ContactButton2;
    private javax.swing.JButton ContactButton3;
    private javax.swing.JTextField Country;
    private javax.swing.JLabel CountryEditLabel;
    private javax.swing.JLabel CountryEditLabel1;
    private javax.swing.JTextField CountryEditTextfield;
    private javax.swing.JTextField CountryEditTextfield1;
    private javax.swing.JLabel CreateAccountLink;
    private javax.swing.JTextField DocumentEditTextfield;
    private javax.swing.JTextField DocumentEditTextfield1;
    private javax.swing.JTextField DocumentNumber;
    private javax.swing.JButton EditDetailsButton;
    private javax.swing.JButton EditDetailsButton1;
    private javax.swing.JLabel EditLoginLabel;
    private javax.swing.JLabel EditLoginLabel1;
    private javax.swing.JLabel EditMessageLabel;
    private javax.swing.JLabel EditMessageLabel1;
    private javax.swing.JLabel EditPasswordLabel;
    private javax.swing.JLabel EditPasswordLabel1;
    private javax.swing.JLabel ExpirationDateLabel;
    private javax.swing.JLabel ExpirationDateLabel1;
    private javax.swing.JTextField ExpirationDateTextField;
    private javax.swing.JTextField ExpirationDateTextField1;
    private javax.swing.JTextField FindLoginTextField;
    private javax.swing.JLabel FindResultLabel;
    private javax.swing.JButton FindUser;
    private javax.swing.JButton GatesButton;
    private javax.swing.JLabel IDEditLabel;
    private javax.swing.JLabel IDEditLabel1;
    private javax.swing.JTextField IDEditTextfield;
    private javax.swing.JTextField IDEditTextfield1;
    private javax.swing.JLabel IDLabel;
    private javax.swing.JLabel IDLabel1;
    private javax.swing.JTextField IDTextField;
    private javax.swing.JTextField IDTextField1;
    private javax.swing.JPanel Login;
    private javax.swing.JButton LoginButton;
    private javax.swing.JTextField LoginEditTextfield;
    private javax.swing.JTextField LoginEditTextfield1;
    private javax.swing.JLabel LoginLabel;
    private javax.swing.JTextField LoginTextField;
    private javax.swing.JTextField LoginTextField1;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JLabel MessageLabel;
    private javax.swing.JLabel MyAccountLabel1;
    private javax.swing.JPanel MyAccountPanel;
    private javax.swing.JButton MyCardsButton;
    private javax.swing.JButton MyCardsButton2;
    private javax.swing.JTextField Name;
    private javax.swing.JLabel NameEditLabel;
    private javax.swing.JLabel NameEditLabel1;
    private javax.swing.JTextField NameEditTextfield;
    private javax.swing.JTextField NameEditTextfield1;
    private javax.swing.JPasswordField Password;
    private javax.swing.JTextField PasswordEditTextfield;
    private javax.swing.JTextField PasswordEditTextfield1;
    private javax.swing.JLabel PasswordLabel;
    private javax.swing.JPasswordField PasswordTextField;
    private javax.swing.JLabel PointsLabel;
    private javax.swing.JLabel PointsLabel1;
    private javax.swing.JTextField PointsTextField;
    private javax.swing.JTextField PointsTextField1;
    private javax.swing.JButton PriceListButton;
    private javax.swing.JPanel Register;
    private javax.swing.JLabel RegisterBackgroundImage1;
    private javax.swing.JButton RegisterButton;
    private javax.swing.JLabel RegisterMessageLabel;
    private javax.swing.JButton RemoveCardButton;
    private javax.swing.JButton RemoveCardButton1;
    private javax.swing.JButton RemoveCardButton2;
    private javax.swing.JButton RemoveUser;
    private javax.swing.JButton SaveDetailsButton;
    private javax.swing.JButton SaveDetailsButton1;
    private javax.swing.JButton SlopeButton;
    private javax.swing.JButton SlopeTrafficButton;
    private javax.swing.JButton SlopeTrafficButton1;
    private javax.swing.JButton SlopeTrafficButton2;
    private javax.swing.JTextField Street;
    private javax.swing.JLabel StreetEditLabel;
    private javax.swing.JLabel StreetEditLabel1;
    private javax.swing.JTextField StreetEditTextfield;
    private javax.swing.JTextField StreetEditTextfield1;
    private javax.swing.JButton SubtractPointsButton;
    private javax.swing.JButton SubtractPointsButton1;
    private javax.swing.JTextField Surname;
    private javax.swing.JLabel SurnameEditLabel;
    private javax.swing.JLabel SurnameEditLabel1;
    private javax.swing.JTextField SurnameEditTextfield;
    private javax.swing.JTextField SurnameEditTextfield1;
    private javax.swing.JLabel UpdateResultLabel;
    private javax.swing.JButton UpdateUser;
    private javax.swing.JLabel UserBackgroundLabel;
    private javax.swing.JLabel UserBackgroundLabel1;
    private javax.swing.JLabel UserBackgroundLabel3;
    private javax.swing.JButton UserLogoutButton;
    private javax.swing.JButton UserLogoutButton1;
    private javax.swing.JButton UserLogoutButton2;
    private javax.swing.JButton UserLogoutButton3;
    private javax.swing.JButton UserLogoutButton4;
    private javax.swing.JPanel UserMainPanel;
    private javax.swing.JLabel UserManagePanelBackgroud;
    private javax.swing.JPanel UserManagmenAdmintPanel;
    private javax.swing.JButton UserMyAccountButton;
    private javax.swing.JButton UserMyAccountButton2;
    private javax.swing.JButton UserMyAccountButton3;
    private javax.swing.JRadioButton UserRadio;
    private javax.swing.ButtonGroup UserRoleChooseGroup;
    private javax.swing.JButton UsersButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JEditorPane jEditorPane1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    // End of variables declaration//GEN-END:variables
}
