package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1



/**
 * Boughtlist generated by hbm2java
 */
public class Boughtlist  implements java.io.Serializable {


     private int boughtlistid;
     private Cardusage cardusage;
     private Itemprice itemprice;

    public Boughtlist() {
    }

    public Boughtlist(int boughtlistid, Cardusage cardusage, Itemprice itemprice) {
       this.boughtlistid = boughtlistid;
       this.cardusage = cardusage;
       this.itemprice = itemprice;
    }
   
    public int getBoughtlistid() {
        return this.boughtlistid;
    }
    
    public void setBoughtlistid(int boughtlistid) {
        this.boughtlistid = boughtlistid;
    }
    public Cardusage getCardusage() {
        return this.cardusage;
    }
    
    public void setCardusage(Cardusage cardusage) {
        this.cardusage = cardusage;
    }
    public Itemprice getItemprice() {
        return this.itemprice;
    }
    
    public void setItemprice(Itemprice itemprice) {
        this.itemprice = itemprice;
    }




}


