package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Cardusage generated by hbm2java
 */
public class Cardusage  implements java.io.Serializable {


     private int useid;
     private Cards cards;
     private Date usedate;
     private Set terminals = new HashSet(0);
     private Set boughtlists = new HashSet(0);

    public Cardusage() {
    }

	
    public Cardusage(int useid, Cards cards, Date usedate) {
        this.useid = useid;
        this.cards = cards;
        this.usedate = usedate;
    }
    public Cardusage(int useid, Cards cards, Date usedate, Set terminals, Set boughtlists) {
       this.useid = useid;
       this.cards = cards;
       this.usedate = usedate;
       this.terminals = terminals;
       this.boughtlists = boughtlists;
    }
   
    public int getUseid() {
        return this.useid;
    }
    
    public void setUseid(int useid) {
        this.useid = useid;
    }
    public Cards getCards() {
        return this.cards;
    }
    
    public void setCards(Cards cards) {
        this.cards = cards;
    }
    public Date getUsedate() {
        return this.usedate;
    }
    
    public void setUsedate(Date usedate) {
        this.usedate = usedate;
    }
    public Set getTerminals() {
        return this.terminals;
    }
    
    public void setTerminals(Set terminals) {
        this.terminals = terminals;
    }
    public Set getBoughtlists() {
        return this.boughtlists;
    }
    
    public void setBoughtlists(Set boughtlists) {
        this.boughtlists = boughtlists;
    }




}


