package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Itemprice generated by hbm2java
 */
public class Itemprice  implements java.io.Serializable {


     private int itempriceid;
     private Pricelist pricelist;
     private Product product;
     private int price;
     private Set boughtlists = new HashSet(0);

    public Itemprice() {
    }

	
    public Itemprice(int itempriceid, Pricelist pricelist, Product product, int price) {
        this.itempriceid = itempriceid;
        this.pricelist = pricelist;
        this.product = product;
        this.price = price;
    }
    public Itemprice(int itempriceid, Pricelist pricelist, Product product, int price, Set boughtlists) {
       this.itempriceid = itempriceid;
       this.pricelist = pricelist;
       this.product = product;
       this.price = price;
       this.boughtlists = boughtlists;
    }
   
    public int getItempriceid() {
        return this.itempriceid;
    }
    
    public void setItempriceid(int itempriceid) {
        this.itempriceid = itempriceid;
    }
    public Pricelist getPricelist() {
        return this.pricelist;
    }
    
    public void setPricelist(Pricelist pricelist) {
        this.pricelist = pricelist;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public int getPrice() {
        return this.price;
    }
    
    public void setPrice(int price) {
        this.price = price;
    }
    public Set getBoughtlists() {
        return this.boughtlists;
    }
    
    public void setBoughtlists(Set boughtlists) {
        this.boughtlists = boughtlists;
    }




}


