package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1



/**
 * Productlist generated by hbm2java
 */
public class Productlist  implements java.io.Serializable {


     private int productlistid;
     private Product product;
     private Terminal terminal;

    public Productlist() {
    }

    public Productlist(int productlistid, Product product, Terminal terminal) {
       this.productlistid = productlistid;
       this.product = product;
       this.terminal = terminal;
    }
   
    public int getProductlistid() {
        return this.productlistid;
    }
    
    public void setProductlistid(int productlistid) {
        this.productlistid = productlistid;
    }
    public Product getProduct() {
        return this.product;
    }
    
    public void setProduct(Product product) {
        this.product = product;
    }
    public Terminal getTerminal() {
        return this.terminal;
    }
    
    public void setTerminal(Terminal terminal) {
        this.terminal = terminal;
    }




}


