package DBClasses;
// Generated 2016-05-01 18:16:39 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Terminal generated by hbm2java
 */
public class Terminal  implements java.io.Serializable {


     private int terminalid;
     private Attraction attraction;
     private Cardusage cardusage;
     private Integer locktime;
     private Set productlists = new HashSet(0);

    public Terminal() {
    }

	
    public Terminal(int terminalid, Attraction attraction, Cardusage cardusage) {
        this.terminalid = terminalid;
        this.attraction = attraction;
        this.cardusage = cardusage;
    }
    public Terminal(int terminalid, Attraction attraction, Cardusage cardusage, Integer locktime, Set productlists) {
       this.terminalid = terminalid;
       this.attraction = attraction;
       this.cardusage = cardusage;
       this.locktime = locktime;
       this.productlists = productlists;
    }
   
    public int getTerminalid() {
        return this.terminalid;
    }
    
    public void setTerminalid(int terminalid) {
        this.terminalid = terminalid;
    }
    public Attraction getAttraction() {
        return this.attraction;
    }
    
    public void setAttraction(Attraction attraction) {
        this.attraction = attraction;
    }
    public Cardusage getCardusage() {
        return this.cardusage;
    }
    
    public void setCardusage(Cardusage cardusage) {
        this.cardusage = cardusage;
    }
    public Integer getLocktime() {
        return this.locktime;
    }
    
    public void setLocktime(Integer locktime) {
        this.locktime = locktime;
    }
    public Set getProductlists() {
        return this.productlists;
    }
    
    public void setProductlists(Set productlists) {
        this.productlists = productlists;
    }




}


